name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: $ {{ secrets.DOCKER_HUB_USERNAME }}/Discount-pipeline:latest$(date-'%Y-%m-%d%H-')

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $ {{ secrets.DOCKER_HUB_USERNAME }}
          password: $ {{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: actions/build-push-action@v2

        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: $ {{ secrets.DOCKER_HUB_USERNAME }}/Discount-pipeline:latest$(date-'%Y-%m-%d%H-')
